### ISSUE TITLE
ERROR: Nothing to send stack:Error: Nothing to send

### ISSUE THREAD

**Issue by loretoparisi** [rosskukulinski/lynx-express#7]
I get this error when sending a metrics:

```
error code: message:Nothing to send stack:Error: Nothing to send
```

I have configured everything as for the docs

```javascript
self.metrics = new Lynx(self._options.metrics.host, self._options.metrics.port, self._options.metrics.statsd);
var statsdMiddleware = LynxExpress(self.metrics);
self.app.use( statsdMiddleware(self._options.metrics.lynx) );
```

and then I have sent a increment metrics with a sampling of 1 of 2 like:

```javascript
self.metrics.increment('api_calls_test_post.int', 0.5);
```

I have added the `on_error` tracking to print out the stack trace:

```
Error: Nothing to send
    at makeError (/node_modules/lynx/lib/lynx.js:15:15)
    at Lynx.send (/node_modules/lynx/lib/lynx.js:403:7)
    at Lynx.count (/node_modules/lynx/lib/lynx.js:310:8)
    at Lynx.increment (/node_modules/lynx/lib/lynx.js:228:8)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at /node_modules/lynx-express/index.js:78:7
    at Layer.handle [as handle_request] (//node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node_modules/express/lib/router/index.js:317:13)
    at /node_modules/express/lib/router/index.js:284:7
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
If I remove the sampling or set to `1.0` it works:

```javascript
self.metrics.increment('api_calls_test_post.int', 1.0);
```

Does this mean that I can ignore that error in the case of sampling?
If so the only thing I could do it would be like

```javascript
on_error = function on_error(error) {
   if( error.message != 'Nothing to send' ) { // ignore sampling errors
        console.error("error:%s code:%d", error.message, error.code);
    }
};
```
because there is no specific `error.code` for that.
Thanks for your help!

**Comment by FilipHarald** [comment]
That is how i solved it aswell. It is related to this issue in Lynx: https://github.com/dscape/lynx/issues/10 .
